### ISSUE TITLE
Git is a Source Code Management (SCM) system not software configuration management system

### ISSUE THREAD

**Issue by gm3dmo** [GovernmentCommunicationsHeadquarters/BoilingFrogs#5]
On Page 8

> For example, an organisation building public service websites would not build a software configuration management system for itself, this is a commodity capability that is best served by well-established tools such as the open source Git.

SCM in the context of git means Source Code Management System rather than a software configuration management system. See: https://en.wikipedia.org/wiki/Comparison_of_open-source_configuration_management_software and https://en.wikipedia.org/wiki/Git_(software)

**Comment by russ-b-ukg** [comment]
Updated
